X=MsgBox("Your computer has coronavirus, do you want to quarantine it?",4+16,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Are you sure?",4+32,"Error") 
X=MsgBox("Fine I'll do it",0+64,"Error") 
X=MsgBox("Failed to quarantine it",2+16,"Error") 

X=MsgBox("Just joking",0+64,"Error") 